name: 'Geth Action'
description: 'Private chain of Ethereum for test using geth'
outputs:
  rpc_url:
    description: "url of JSON RPC"
    value: http://localhost:8501
runs:
  using: "composite"
  steps:
    - id: init
      run: docker-compose run --rm geth ./scripts/init.sh
      shell: bash
    - id: run
      run: docker-compose up -d
      shell: bash
